### ISSUE TITLE
Agregar un menu para seleccionar distintos personajes

### ISSUE THREAD

**Issue by BuggyOffmoz** [bkerz/VoidShips#1]
Crear un menú básico con la funcionalidad de seleccionar un personaje antes de iniciarte en el mundo ("First World")

--------------------------------------------------------------------------------------------------------------------------------

**Para tener en cuenta u opcional:**

```
°De momento tenemos un personaje ("Max" y es de Ataque melee) así que no hay mas de uno que seleccionar.

°Por ahora no maneja tantos datos (Como vida/Velocidad/Ataque) así que con el hecho de que se puedan seleccionar
 para aparecer esta perfecto.

°Si no se selecciona ningún personaje no podrías pasar al mundo, no olvidarse

°Su finalidad es hacer que el spawn del personaje entienda cual fue el seleccionado, no mas que eso
```

**TAREAS ESPECIFICAS**

- [x] Poder Seleccionar el personaje
- [x] Poder volver al menú inicial (MainMenu/escena)
- [x] Poder dar paso al mundo ("First World")

**Comment by bkerz** [comment]
@BuggyOffmoz ¿El Menú no tendrá funcionalidad? Osea, ¿está bien que solo nos enfoquemos en la apariencia del Menú o se le dará también una funcionalidad?

**Comment by BuggyOffmoz** [comment]
Tomare esta tarea

**Comment by BuggyOffmoz** [comment]
RESUMEN:
Ya testee y asigne todo lo necesario para esta issues

PROBLEMAS:
Sin problemas/Crasheos
