### ISSUE TITLE
Añadir Timer para finalizar el juego

### ISSUE THREAD

**Issue by BuggyOffmoz** [bkerz/VoidShips#2]
**Crear y añadir un temporizador para poder darle una finalidad al juego de forma positiva.**
---------------------------------------------------------------------------------------------------

- [x] El temporizador podrá ser visible en todo momento en la escena "First World"
- [x] Podrá ser representado de la forma que quieran siempre que sea intuitivo
- [x] Debe ser de 5 minutos (esto es algo que podrá cambiar mientras se avance en el proyecto)
- [x] Debe ser independiente a cualquier tipo de escena y/u enemigo dentro del árbol de escenas

----------------------------------------------------------------------------------------------------
*ACTUALIZACIÓN*

- [x] Una vez finalizado el temporizador tendrias que terminar en el menú principal, se podría
   llevar a cabo de una forma cómoda (Algún aviso con un botón, esto estaría sujeto a cambios
   en un futuro)

**Comment by bkerz** [comment]
@BuggyOffmoz  ¿Luego de que el Timer finalice qué pasará? ¿Se tendrá que mostrar una pantalla o algo así?

**Comment by bkerz** [comment]
Yo me agarro este issue.
