### ISSUE TITLE
Programar un movimiento general en todos los tipos de enemigos

### ISSUE THREAD

**Issue by bkerz** [bkerz/VoidShips#6]
De momento, solo algunos enemigos se mueven de una manera especifica y los demás no tienen movimiento. En esta tarea se creará un comportamiento de movimiento general para cada tipo de enemigo, 3 por ahora.

**Subtareas**
- [x] Documentar los 3 tipos de enemigo junto con la manera en la que se comportarán
- [x] Programar movimiento para cada tipo de enemigo
- [x] Crear Assets base para cada tipo de enemigo

**Comment by BuggyOffmoz** [comment]
**_Para el primer enemigo podría tener el movimiento básico de perseguir/acercarse al jugador con la intención de 
"Atacarla" (simplemente tocando al player para generarle daño)_**

```
Este enemigo aparecería en el primer segundo de juego en adelante.
Su velocidad podría variar (siendo esta de 200 a 250) para el nivel 1
Una vida que resista entre uno y dos ataques del jugador para una dificultad básica
```

**Comment by BuggyOffmoz** [comment]
**_Para el segundo enemigo podría tener un movimiento mas lento (y por ende ser un poco mas fuerte)
Afectando así su vida y ataque (El comportamiento podría seguir siendo básico al igual que el enemigo uno)_**

```
Este enemigo podría aparecer en cuanto pase el primer minuto de juego para dar el primer dinamismo
Su velocidad podría ser lenta y un poco variada desde 50 a 100 para el nivel 1
Una vida que resista entre 2/3 ataques del jugador
```

**Comment by BuggyOffmoz** [comment]
**_Para el tercer enemigo podría tener un normal pero siendo más débil ya que este podría esta atacando a distancia
Al ser un enemigo de rango su vida sería menor a lo normal y el comportamiento podría ser mes defensivo manteniendo
una distancia clara entre el y el jugador_**

```
Este enemigo aparecería en el 2do minuto de juego y así terminar de agregar el dinamismo básico para el juego.
Su velocidad podría se un poco mayor a la normal variando entre 250 a 300 de velocidad para el nivel 1.
Una vida que no suele resistir más de un solo golpe del jugador.
```
